function main
%function main runs the simple Graphical User Interface - simple application
%   There are no input and output arguments

clear all;
close all;
clc;

global filename filepath text5 Wspeed Wdir AirTemp position1 position2 position3

global text1 text2 text3 text4

    disp(datestr(now))
    close all;
   
%% creating simple GUI --- definition of start window application

f = figure( 'units', 'pixels',...
            'position', [450 150 770 450],... 
            'menubar', 'none',...
            'name','Wind Data Application - simple weather analysis',...
            'numbertitle','off',...
            'resize','off');

%% creating application menu

menu = uimenu('Parent',f,'Label','File'); 
        uimenu(menu,'label','Load','Callback','load_data; clear ans;');
%         uimenu(menu,'label','Load','Callback',@loadFile);
        uimenu(menu,'label','Save','Callback','uisave;');
        uimenu(menu,'label','Exit','Callback','close all;clear;clc;'); % Method of putting exact string as commands or functions   
        
%% creating buttons - choose year
button1 = uicontrol('parent',f,...
    'position',[10 50 180 30],...
    'string','Chose Year / Load Data',...
    'callback','choose_years;');      

%% plotting statistics
    
button2 = uicontrol('parent',f,...
    'position',[200 50 180 30],...
    'string','Calculate Statistics',...
    'callback','plot_data;');

%% plotting dataset
    
button3 = uicontrol('parent',f,...
    'position',[390 50 180 30],...
    'string','Plot Dataset',...
    'callback','plot_dataset;');

%% presenting the info about chosen file
text5 =uicontrol('parent',f,...
    'position',[10 10 150 30],...
    'style','text',...
    'string','File:');

text1 = uicontrol('parent', f,...
    'position', [300 360 180 30],...
    'style', 'text',...
    'string', 'Statistics of Chosen Year');

%% data statistics

text2 = uicontrol('parent', f,...
    'position', [200 300 180 30],...
    'style', 'text',...
    'string', 'Mean Wind Speed m/s');

position1 = uicontrol('parent',f,...
    'position',[375 310 180 30],...
    'style', 'edit',...
    'string','');

text3 = uicontrol('parent', f,...
    'position', [200 240 180 30],...
    'style', 'text',...
    'string', 'Standard Deviation');

position2 = uicontrol('parent',f,...
    'position',[375 250 180 30],...
    'style', 'edit',...
    'string','');

text4 = uicontrol('parent', f,...
    'position', [200 180 180 30],...
    'style', 'text',...
    'string', 'Maximum Wind Speed');

position3 = uicontrol('parent',f,...
    'position',[375 190 180 30],...
    'style', 'edit',...
    'string','');

%% Show Table

button4 = uicontrol('parent',f,...
    'position',[580 50 180 30],...
    'string','Show Table',...
    'callback','show_table;');


end

