%% Figure
global text5

f = figure( 'units', 'pixels',...
            'position', [450 150 770 450],... 
            'menubar', 'none',...
            'name','Database Analysis',...
            'numbertitle','off',...
            'resize','off');
        
%% Menubar

menu = uimenu('Parent',f,'Label','File'); 
        uimenu(menu,'label','Save Plot','Callback','savepng;');
        uimenu(menu,'label','Exit','Callback','close all;clear;clc;');
 
%% creating buttons 1
button1 = uicontrol('parent',f,...
    'position',[200 50 180 30],...
    'string','Average of Selected Patient_ID',...
    'callback','avg_selected_id;');  

button2 = uicontrol('parent',f,...
    'position',[400 50 180 30],...
    'string','Plot Table',...
    'callback','Database_Analysis;');

%% Creating bars to get avg of band_ts, gsr_s0, ibi_s0 and tmp_s0

global text1 text2 text3 text4 position1 position2 position3 position4

text1 = uicontrol('parent', f,...
    'position', [200 300 180 30],...
    'style', 'text',...
    'string', 'Mean Band_TS');

position1 = uicontrol('parent',f,...
    'position',[375 310 180 30],...
    'style', 'edit',...
    'string','');

text2 = uicontrol('parent', f,...
    'position', [200 240 180 30],...
    'style', 'text',...
    'string', 'Mean GSR_S0');

position2 = uicontrol('parent',f,...
    'position',[375 250 180 30],...
    'style', 'edit',...
    'string','');

text3 = uicontrol('parent', f,...
    'position', [200 180 180 30],...
    'style', 'text',...
    'string', 'Mean IBI_S0');

position3 = uicontrol('parent',f,...
    'position',[375 190 180 30],...
    'style', 'edit',...
    'string','');

text4 = uicontrol('parent', f,...
    'position', [200 120 180 30],...
    'style', 'text',...
    'string', 'Mean TMP_S0');

position4 = uicontrol('parent',f,...
    'position',[375 130 180 30],...
    'style', 'edit',...
    'string','');

%% Writing selected patient_id

text5 = uicontrol('parent', f,...
    'position', [10 400 500 30],...
    'style', 'text',...
    'string', 'Selected Patient_id: ');

