function wind_data = importfile2(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  WIND_DATA = IMPORTFILE1(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  WIND_DATA = IMPORTFILE1(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  wind_data = importfile1("G:\!DYDAKTYKA-ERASMUS-LATO-2020-2021\Matlab_Programming\Lecture 7 - 8 Programming GUI - Final Project\7+021.253E_+050.930N_50m_AllData.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Apr-2021 11:44:43

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Day", "HourUTC", "Speedms", "AirTempC", "WindDir"];
opts.VariableTypes = ["datetime", "string", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "HourUTC", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "HourUTC", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Day", "InputFormat", "yyyy-MM-dd");

% Import the data
wind_data = readtable(filename, opts);

end